# Generated by Django 6.0.3 on 2026-05-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoo',
            name='srno',
        ),
        migrations.RemoveField(
            model_name='todoo',
            name='status',
        ),
        migrations.AddField(
            model_name='todoo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='todoo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
