# Generated by Django 6.0.3 on 2026-05-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_application', '0002_remove_todoo_srno_remove_todoo_status_todoo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoo',
            name='id',
        ),
        migrations.AddField(
            model_name='todoo',
            name='srno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
